### ISSUE TITLE
Jest addon should only work inside test/

### ISSUE THREAD

**Issue by satazor** [moxystudio/eslint-config-moxy#31]
See: https://github.com/reactjs/redux/blob/de94043033fdd13dc4fa3cede2943143c6d28942/.eslintrc.js#L4

**Comment by satazor** [comment]
Actually, this should be an option because some of our projects have tests near the source code.

**Comment by satazor** [comment]
Actually this should be opt-in and not the default. Perhaps a different addon?

**Comment by acostalima** [comment]
@satazor @andregoncalvesdev  @AfonsoVReis 

According to ESLint's docs, the configuration can be modified under `overrides` key in `.eslintrc.*`. I have been experimenting a bit and below is the best I've achieved so far.

- I had to make the the top-level `.eslintrc.json` into `.eslintrc.js` instead:

```js
module.exports = {
    'root': true,
    'extends': [
        './es5.js',
        './addons/node.js',
        './addons/jest.js',
    ],
    'rules': {
        'quote-props': [2, 'always'],
    },
    'overrides': [require('./addons/overrides/jest-test-dir')],
};
```

where `jest-test-dir.js` is:

```js
'use strict';

module.exports = {
    'env': {
        'jest/globals': false,
    },
    'files': ['!test/**/*.js'],
    'rules': {
        'jest/no-disabled-tests': 0,
        'jest/no-focused-tests': 0,
        'jest/no-identical-title': 0,
        'jest/valid-expect': 0,
    },
};
``` 

The above works just fine, but has the following downsides/problems:

- The ESLint config must be `.js` instead of `.json`, if we wish to use the override as a module
- ESLint is not seeing changes made to `jest-test-dir.js` probably because we're using `require`, which is an inconvenient. I do not yet know how to fix this.

Feedback is welcome! 😄

**Comment by acostalima** [comment]
I think I got it. I was not aware that it was possible to extend a config with `overrides`:

```js
// ./addons/overrides/jest-test-files.js`
'use strict';

module.exports = {
    'overrides': [{
        'env': {
            'jest/globals': false,
        },
        'files': ['!test/**/*.js'],
        'rules': {
            'jest/no-disabled-tests': 0,
            'jest/no-focused-tests': 0,
            'jest/no-identical-title': 0,
            'jest/valid-expect': 0,
        },
    }],
};
```

```js
// ./.eslintrc.json
{
    "root": true,
    "extends": [
        "./es5.js",
        "./addons/node.js",
        "./addons/jest.js",
        "./addons/overrides/jest-test-dir.js"
    ],
    "rules": {
        "quote-props": [2, "always"]
    }
}
```

What do you think?

**Comment by satazor** [comment]
I think we do not need to create `jest-test-dir` but put all of this in the `addons/jest.js`.

Regarding the `files` it should be based on the default patterns of jest + add a `test` folder because of utilities I mentioned above.

```js
[
   '!**/__tests__/**/*.js',
   '!**/?(*.)(spec|test).js',
   '!test/**/*.js',
]
```

**Comment by acostalima** [comment]
@satazor thanks! 👍 
It is working already. I'm just finalizing the tests. I'll open a PR shortly.

**Comment by satazor** [comment]
I've updated the patterns. I've removed `.jsx` support because it's a bad practice.
